[package]
name = "ns-bindings"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
objc = "0.2.7"
cocoa = "0.26.0"
core-foundation-sys = "0.8.7"
core-foundation = "0.10.0"
nix = "0.29.0"